language: node_js
node_js:
  - "0.10"
branches:
  only:
  - master
  - documentation
before_install: npm install -g grunt-cli
install: npm install
after_success:
  - grunt jsdoc
  - git add -A
  - git stash
  - git pull origin/gh-pages gh-pages
  - git branch
  - git stash apply
  - cp -r gh-pages/* .
  - rm -r gh-pages/
  - rm index.html
  - mv SurfNPerf.html index.html
  - git add -A
  - git commit -m "Automated documentation update"
  - git push origin gh-pages
  - git checkout master
  - git branch -d gh-pages