language: node_js
node_js:
  - "0.10"
branches:
  only:
  - master
  - documentation
before_install: npm install -g grunt-cli
install: npm install
after_success:
  - git remote set-url origin https://github.com/rachbrown151/Surf-N-Perf.git
  - git config --global user.email "shayanp@seas.upenn.edu"
  - git config --global user.name "Shayan Patel"
  - grunt jsdoc
  - git add -A
  - git status
  - git stash
  - git checkout -b gh-pages
  - ls
  - rm -r *
  - ls
  - git stash apply
  - ls
  - cp -r gh-pages/* .
  - rm -r gh-pages/
  - rm index.html
  - mv SurfNPerf.html index.html
  - git add -A
  - git commit -m "Automated documentation update"
  - git push origin gh-pages
  - git checkout master
  - git branch -d gh-pages
