language: node_js
node_js:
  - "0.10"
env:
  global:
    - GH_REF https://github.com/rachbrown151/Surf-N-Perf
    - secure: "lDcNE9r8busJxdPLOWCDVZbwLP7JVEAGJkJf8WTxDn7d3M/MVXsAoCifPzZLFp0GOUA9HBEoYX0QVQGc3VxHC4m8CjQczMnABuwI+zozCyif8Ql9OWKc7msWGxfj+LG8WWR9C+P6I5oRwF0cx5eYBMj4IUsYPivCMy5wJqsi8ug="
branches:
  only:
    - master
    - documentation
before_install: npm install -g grunt-cli
install:
  - npm install
after_success:
  - "git remote set-url origin https://github.com/rachbrown151/Surf-N-Perf.git"
  - "git config --global user.email \"rabrown@seas.upenn.edu\""
  - "git config --global user.name \"Rachel Brown\""
  - grunt jsdoc
  - git add -A
  - git status
  - git stash
  - git checkout -b gh-pages
  - ls
  - "rm -r *"
  - ls
  - git stash apply
  - ls
  - "cp -r gh-pages/* ."
  - rm -r gh-pages/
  - rm index.html
  - mv SurfNPerf.html index.html
  - git add -A
  - "git commit -m \"Automated documentation update\""
  - git push origin gh-pages
  - git checkout master
  - git branch -d gh-pages
